name: grab_tags
description: Demonstrates how to use the screen_capture_event plugin.
version: 1.0.0+2
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0" 
dependencies:
  flutter:
    sdk: flutter

  screen_capture_event: 
    path: ../ 
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^1.3.2

  google_ml_kit_for_korean: ^0.0.8 #https://pub.dev/packages/google_ml_kit_for_korean/changelog
  bringtoforeground: ^0.0.2
  move_to_background: ^1.0.2 #https://pub.dev/packages/move_to_background

  flutter_tags: ^0.4.9+1

  flutter_observer: ^2.0.0 #https://pub.dev/packages/flutter_observer
  sqflite: #https://flutter-ko.dev/docs/cookbook/persistence/sqlite
  intl: ^0.17.0

  #image_gallery_saver: ^1.7.1
  #path_provider: #https://pub.dev/packages/path_provider
  #

  #flutter_background_service: ^0.1.5
  url_launcher: ^6.0.17

  provider: ^6.0.1
  flutter_screenutil: ^5.0.0+2
  system_alert_window: ^0.5.0+1

  in_app_purchase: ^2.0.0
  shared_preferences: ^2.0.0
  permission_handler: ^8.3.0
  google_mobile_ads: ^1.0.1
  image: ^3.1.0
  flutter_local_notifications: ^9.1.4
  rxdart: ^0.27.3
  introduction_screen: ^2.1.0
  get_storage: ^2.0.3
  salomon_bottom_bar: ^3.2.0
  badges: ^2.0.2
  empty_widget: ^0.0.5
  package_info_plus: ^1.3.0 #https://pub.dev/packages/package_info_plus
  flutter_dialogs: ^2.1.1
  icon_animator: ^0.0.4
  neon: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^1.0.0

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  fullscreen: true