name: screen_capture_event
description: Catch screen capture (Screenshot & Screen Record) event for Android and iOS
version: 1.0.0+1
homepage: https://github.com/nizwar/screen_capture_event.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^8.1.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: id.nizwar.screen_capture_event
        pluginClass: ScreenCaptureEventPlugin
      ios:
        pluginClass: ScreenCaptureEventPlugin
